var a;
console.log('O tipo de a eh: '+ typeof(a));
a = 1;
console.log('O tipo de a eh: '+ typeof(a));
a = "Palavra";
console.log('O tipo de a eh: '+ typeof(a));
a = false;
console.log('O tipo de a eh: '+ typeof(a));
a = [];
console.log('O tipo de a eh: '+ typeof(a));